import type { WxtI18n } from "wxt/browser";

/**
 * A valid i18n message name, as generated by WXT from `messages.json`
 */
export type MessageName = Parameters<WxtI18n["getMessage"]>[0];
type MessageSubstitutions = Parameters<WxtI18n["getMessage"]>[1];

// Prevent the case-insensitive check from silently accepting any `string`
type AssertExactMessageNames<T extends string> = string extends T ? never : T;

/**
 * A message name that exists in `messages.json`, ignoring casing
 */
export type CaseInsensitiveMessageName<T extends string> = T extends string
  ? Lowercase<T> extends Lowercase<AssertExactMessageNames<MessageName>>
    ? T
    : never
  : never;

/**
 * Gets a localized message when the message name is valid but not necessarily exact-case
 * @param {CaseInsensitiveMessageName<T>} messageName the message name
 * @param {MessageSubstitutions} [substitutions] optional substitutions for the message
 * @returns {string} the localized message
 */
export const GetCaseInsensitiveMessage = <const T extends string>(
  messageName: CaseInsensitiveMessageName<T>,
  substitutions?: MessageSubstitutions,
): string => browser.i18n.getMessage(messageName as MessageName, substitutions);
