name: nextrelease
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [labeled, unlabeled, edited, synchronize]

jobs:
  sync:
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' && github.head_ref == 'nextrelease' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        registry-url: 'https://registry.npmjs.org'
    - uses: dropseed/nextrelease@v1
      with:
        prepare_cmd: |
          sed -i -e "s/v$LAST_VERSION/v$NEXT_VERSION/g" README.md
          npm version $NEXT_VERSION --no-git-tag-version --allow-same-version
        publish_cmd: |
          git tag -a v$VERSION_MAJOR -m Version $VERSION_MAJOR -f && git push origin v$VERSION_MAJOR -f
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tag_prefix: v
        next_branch: nextrelease
